version: '2.1'

services:
  komodo-core:
    env_file:
      - .env
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - core
    image: monaize/komodo-ac:dev
    command:
      -printtoconsole=1
      -server=1
      -txindex=1
      -addressindex=1
      -timestampindex=1
      -spentindex=1
      -uacomment=bitcore
      -showmetrics=0
      -rpcport=8334
      -rpcuser=bitcoin
      -rpcpassword=local321
      -zmqpubrawtx=tcp://0.0.0.0:8332
      -zmqpubhashblock=tcp://0.0.0.0:8332
      -whitelist=127.0.0.1
      -rpcallowip=127.0.0.1
      -rpcallowip=172.0.0.0/8
      -ac_supply=${AC_SUPPLY}
    volumes:
      - komodo-data:/home/komodo/.komodo
      - zcash-params:/home/komodo/.zcash-params

  komodo-insight:
    env_file:
      - .env
    networks:
      - core
    image: monaize/insight:0.3
    ports:
      - 3001:3001


volumes:
  komodo-data:
  zcash-params:
    external: true

networks:
  core:
